package com.zara.parser;

import java.util.ArrayList;
import java.util.List;
import com.zara.lexer.Token;
import com.zara.lexer.TokenType;
import com.zara.parser.ast.BinaryOpNode;
import com.zara.parser.ast.Expression;
import com.zara.parser.ast.NumberNode;
import com.zara.parser.ast.StringNode;
import com.zara.parser.ast.VariableNode;
import com.zara.interpreter.instruction.AssignInstruction;
import com.zara.interpreter.instruction.IfInstruction;
import com.zara.interpreter.instruction.Instruction;
import com.zara.interpreter.instruction.PrintInstruction;
import com.zara.interpreter.instruction.RepeatInstruction;

// This class converts a list of tokens into executable instructions (AST → Instructions)
// It performs parsing (syntax analysis)
public class Parser {

    // List of tokens generated by the Tokenizer
    private final List<Token> tokens;

    // Current position in the token list
    private int pos = 0;

    // Constructor
    public Parser(List<Token> tokens) {
        this.tokens = tokens;
    }

    // Look at current token without consuming it
    private Token peek() {
        return tokens.get(pos);
    }

    // Consume current token and move forward
    private Token consume() {
        return tokens.get(pos++);
    }

    // Check if current token matches a specific type
    private boolean check(TokenType t) {
        return peek().getType() == t;
    }

    // ===== MAIN PARSE FUNCTION =====
    // Converts tokens into a list of Instructions
    public List<Instruction> parse() {

        List<Instruction> instructions = new ArrayList<>();

        // Loop until we reach end of file
        while (!check(TokenType.EOF)) {

            // Skip empty lines
            if (check(TokenType.NEWLINE)) {
                consume();
                continue;
            }

            // Skip stray INDENT tokens (safety)
            if (check(TokenType.INDENT))
                consume();

            if (check(TokenType.EOF))
                break;

            // Parse a single instruction
            instructions.add(parseInstruction());

            // Consume newline after instruction
            if (check(TokenType.NEWLINE))
                consume();
        }

        return instructions;
    }

    // Decide which type of instruction to parse
    private Instruction parseInstruction() {

        Token t = peek();

        return switch (t.getType()) {

            case SET -> parseAssign();     // assignment
            case SHOW -> parsePrint();    // print/output
            case WHEN -> parseIf();       // conditional
            case LOOP -> parseRepeat();   // loop

            default -> throw new RuntimeException(
                    "Unexpected token '" + t.getValue() + "' on line " + t.getLine());
        };
    }

    // ===== ASSIGNMENT: set x = expression =====
    private Instruction parseAssign() {

        consume(); // consume 'set'

        String name = consume().getValue(); // variable name

        consume(); // consume '='

        // Create AssignInstruction node
        return new AssignInstruction(name, parseExpression());
    }

    // ===== PRINT: show expression =====
    private Instruction parsePrint() {

        consume(); // consume 'show'

        return new PrintInstruction(parseExpression());
    }

    // ===== IF CONDITION =====
    private Instruction parseIf() {

        consume(); // consume 'when'

        Expression condition = parseExpression(); // condition

        consume(); // consume ':'

        // Skip newline if present
        if (check(TokenType.NEWLINE))
            consume();

        // Parse the "then" block (indented block)
        List<Instruction> thenBody = parseBlock();

        // Default empty else block
        List<Instruction> elseBody = new ArrayList<>();

        // Handle optional "otherwise"
        if (check(TokenType.OTHERWISE)) {

            consume(); // consume 'otherwise'
            consume(); // consume ':'

            if (check(TokenType.NEWLINE))
                consume();

            elseBody = parseBlock(); // parse else block
        }

        return new IfInstruction(condition, thenBody, elseBody);
    }

    // ===== LOOP =====
    private Instruction parseRepeat() {

        consume(); // consume 'loop'

        // Get loop count
        double raw = Double.parseDouble(consume().getValue());

        // Ensure it's a non-negative integer
        if (raw != Math.floor(raw) || raw < 0)
            throw new RuntimeException(
                    "loop count must be a non-negative integer, got: " + raw);

        int count = (int) raw;

        consume(); // consume ':'

        if (check(TokenType.NEWLINE))
            consume();

        // Create loop instruction with block body
        return new RepeatInstruction(count, parseBlock());
    }

    /*
     * BLOCK PARSER
     * Handles INDENT / DEDENT structure (like Python blocks)
     */
    private List<Instruction> parseBlock() {

        List<Instruction> body = new ArrayList<>();

        // If no INDENT → no block
        if (!check(TokenType.INDENT)) {
            return body;
        }

        consume(); // consume INDENT

        // Continue until DEDENT (block end)
        while (!check(TokenType.EOF) && !check(TokenType.DEDENT)) {

            // Skip empty lines
            if (check(TokenType.NEWLINE)) {
                consume();
                continue;
            }

            // Parse instruction inside block
            body.add(parseInstruction());

            if (check(TokenType.NEWLINE)) {
                consume();
            }
        }

        // Consume DEDENT (end of block)
        if (check(TokenType.DEDENT)) {
            consume();
        }

        return body;
    }

    // ===== EXPRESSION PARSING =====

    private Expression parseExpression() {
        return parseComparison(); // highest-level expression
    }

    // Comparison: > < == != <= >=
    private Expression parseComparison() {

        Expression left = parseAddSub();

        if (check(TokenType.GREATER) || check(TokenType.LESS) ||
                check(TokenType.EQEQ) || check(TokenType.NOT_EQ) ||
                check(TokenType.LESS_EQ) || check(TokenType.GREATER_EQ)) {

            String op = consume().getValue();

            // Build binary operation node
            left = new BinaryOpNode(left, op, parseAddSub());
        }

        return left;
    }

    // Addition / Subtraction
    private Expression parseAddSub() {

        Expression left = parseTerm();

        while (check(TokenType.PLUS) || check(TokenType.MINUS)) {

            String op = consume().getValue();

            // Build binary operation
            left = new BinaryOpNode(left, op, parseTerm());
        }

        return left;
    }

    // Multiplication / Division
    private Expression parseTerm() {

        Expression left = parsePrimary();

        while (check(TokenType.STAR) || check(TokenType.SLASH)) {

            String op = consume().getValue();

            left = new BinaryOpNode(left, op, parsePrimary());
        }

        return left;
    }

    // Base values (numbers, strings, variables)
    private Expression parsePrimary() {

        Token t = consume();

        return switch (t.getType()) {

            case NUMBER ->
                new NumberNode(Double.parseDouble(t.getValue()));

            case STRING ->
                new StringNode(t.getValue());

            case IDENTIFIER ->
                new VariableNode(t.getValue());

            default -> throw new RuntimeException(
                    "Expected a value but got '" + t.getValue() +
                            "' on line " + t.getLine());
        };
    }
}
