package com.zara.lexer;

public enum TokenType {
    NUMBER, STRING, IDENTIFIER,
    PLUS, MINUS, STAR, SLASH,
    GREATER, LESS, EQUALS, EQEQ, NOT_EQ, LESS_EQ, GREATER_EQ,
    SET, SHOW, WHEN, LOOP, OTHERWISE, TRUE, FALSE,
    INDENT, DEDENT, COLON, NEWLINE, EOF
}