package com.zara.interpreter;

import java.util.List;
import com.zara.interpreter.instruction.*;
import com.zara.runtime.*;

/**
 * Interpreter is responsible ONLY for executing instructions.
 *
 * NOTE:
 * - It does NOT handle tokenization or parsing in the long term.
 * - The run() method is temporarily kept for backward compatibility.
 */
public class Interpreter {

    /**
     * Core execution engine of the interpreter.
     *
     * Takes a list of instructions (generated by the parser)
     * and executes them sequentially using a shared Environment.
     *
     * @param instructions List of parsed instructions to execute
     */
    public void execute(List<Instruction> instructions) {

        // Environment stores runtime data (variables, values, etc.)
        Environment env = new Environment();

        // Execute each instruction one by one
        for (Instruction instruction : instructions) {
            try {
                // Each instruction knows how to execute itself
                instruction.execute(env);

            } catch (Exception e) {
                // Catch runtime errors and wrap them with meaningful context
                throw new RuntimeException(
                    "Runtime Error at "
                    + instruction.getClass().getSimpleName()
                    + ": " + e.getMessage()
                );
            }
        }
    }

    /**
     * TEMPORARY METHOD (Backward Compatibility)
     *
     * This method runs the full pipeline:
     * 1. Tokenization
     * 2. Parsing
     * 3. Execution
     *
     * WHY IT EXISTS:
     * - Existing tests and modules depend on this method
     * - Prevents breaking the current pipeline during refactoring
     *
     * FUTURE:
     * - This method will be removed once Main.java fully handles the pipeline
     *
     * @param sourceCode Raw source code as input
     */
    public void run(String sourceCode) {

        // ------------------ STEP 1: TOKENIZATION ------------------
        // Convert raw source code into tokens
        com.zara.lexer.Tokenizer tokenizer =
                new com.zara.lexer.Tokenizer(sourceCode);

        java.util.List<com.zara.lexer.Token> tokens =
                tokenizer.tokenize();

        // ------------------ STEP 2: PARSING ------------------
        // Convert tokens into executable instructions
        com.zara.parser.Parser parser =
                new com.zara.parser.Parser(tokens);

        java.util.List<com.zara.interpreter.instruction.Instruction> instructions =
                parser.parse();

        // ------------------ STEP 3: EXECUTION ------------------
        // Execute the parsed instructions using the new execution engine
        execute(instructions);
    }
}
