package com.zara.interpreter;

import com.zara.lexer.*;
import com.zara.parser.*;
import com.zara.interpreter.instruction.*;
import com.zara.runtime.*;

import java.util.List;

/**
 * Interpreter is responsible ONLY for executing instructions.
 *
 * NOTE:
 * - It does NOT handle tokenization or parsing in the long term.
 * - The run() method is temporarily kept for backward compatibility.
 */
public class Interpreter {

    /**
     * Core execution engine of the interpreter.
     *
     * Takes a list of instructions (generated by the parser)
     * and executes them sequentially using a shared Environment.
     *
     * @param instructions List of parsed instructions to execute
     */
    public void execute(List<Instruction> instructions) {

        // Environment stores runtime data (variables, values, etc.)
        Environment env = new Environment();

        // Execute each instruction one by one
        for (Instruction instruction : instructions) {
            try {
                instruction.execute(env);

            } catch (Exception e) {
                throw new RuntimeException(
                    "Runtime Error at "
                    + instruction.getClass().getSimpleName()
                    + ": " + e.getMessage()
                );
            }
        }
    }

    /**
     * TEMPORARY METHOD (Backward Compatibility)
     */
    public void run(String sourceCode) {

        // STEP 1: TOKENIZATION
        Tokenizer tokenizer = new Tokenizer(sourceCode);
        List<Token> tokens = tokenizer.tokenize();

        // STEP 2: PARSING
        Parser parser = new Parser(tokens);
        List<Instruction> instructions = parser.parse();

        // STEP 3: EXECUTION
        execute(instructions);
    }
}